### PR TITLE
try redirect

### PR DESCRIPTION
**Pull request by chuckwagoncomputing**

### CODE REVIEW

**Comment by rusefillc** [comment]
it seems to me that ``https://wiki.rusefi.com`` is not a valid page because of the /Home drama

it seems to me that this PR is removing the hack which does ``https://wiki.rusefi.com`` to ``https://wiki.rusefi.com/Home`` redirect

you are the boss of this effort please confirm that you are interested to go forward with the change

**Comment by chuckwagoncomputing** [comment]
Maybe I just don't understand, but I can't see how what exists currently could be changing wiki.rusefi.com to wiki.rusefi.com/Home

**Comment by chuckwagoncomputing** [comment]
I don't understand what is going on at all. Here's what it looks like to me:
1. If I visit wiki.rusefi.com, I get a 302 Redirect to wiki.rusefi.com/Home
2. If I visit rusefi.com/docs/wiki, I get a 302 Redirect to rusefi.com/Home
3. If I visit wiki.rusefi.com/Home, I get the content at rusefi.com/docs/wiki/Home, which looks like a Rewrite. Where this rule is I don't know, but it appears to be the result of how it is configured on the 1&1 interface.

**Comment by rusefillc** [comment]
I agree that it makes no sense. On the other hand it looks like https://wiki.rusefi.com is in fact redirected to https://wiki.rusefi.com/Home _somehow_ and this file is the only relevant file I am aware of

reminder that wiki.rusefi.com maps to docs/wiki which seems to be the way which glues https://wiki.rusefi.com to that docs/wiki rule

merged let's observe how it goes!

**Comment by chuckwagoncomputing** [comment]
That doesn't appear to have changed the behaviour. I wonder if Apache needs to be restarted or something?

**Comment by rusefillc** [comment]
I've looked via SFTP and .htaccess file has not been updated

**Pull request merged**
