### PR TITLE
Add workflow to upload

### PR DESCRIPTION
**Pull request by chuckwagoncomputing**
Please make backup before merging, as you mentioned.

Requires RUSEFI_SSH_USER, RUSEFI_SSH_PASS, and RUSEFI_SSH_SERVER secrets

### CODE REVIEW

**Comment by rusefillc** [comment]
@chuckwagoncomputing as my dentist says "great news that did not work out!"

**Comment by chuckwagoncomputing** [comment]
I'm very suspicious there's something wrong with your secrets.

**Comment by rusefillc** [comment]
Well you have a point

image

**Comment by rusefillc** [comment]
Adding secrets has helped!

**Pull request merged**
